### ISSUE TITLE
Add documents page

### ISSUE THREAD

**Issue by Ailrun** [CUTE-Lang/miniCUTE#66]
**Is your feature request related to a problem? Please describe.**
Checking Haddock/doxygen document is too hard.

**Describe the solution you'd like**
Deploy Haddock document/doxygen on somewhere, e.g., github page, ...

**Comment by ENvironmentSet** [comment]
what about [now](https://zeit.co/now)? I haven't used this but I heard that it is quite good.
fully-automated + can work with GitHub pages.

**Comment by Ailrun** [comment]
@ENvironmentSet a problem is it requires a separated engine to build the haddock page. Maybe it is not that hard to build one, so I will consider one.

**Comment by Ailrun** [comment]
I'm not sure whether or not there is a service supporting both Haddock and Doxygen...
Maybe we need to use GitHub page in a manual way.

**Comment by ENvironmentSet** [comment]
Then what about [netlify](https://www.netlify.com)?
I'm using this with Gatsby, this is really nice.

**Comment by Ailrun** [comment]
Netlify does not support Haskell, as far as I know.

**Comment by Ailrun** [comment]
Resolved by 098eb00b413e95f7a487e2f2210accfddebb8639.

**Comment by Ailrun** [comment]
The page does not work well because of https://github.com/commercialhaskell/stack/issues/4971.
The issue does not happen with stack@1.9.3, so I think we should somehow revert the version of stack in the stack docker image of FpCo.

**Comment by Ailrun** [comment]
Now fixed.
